<img src=images/gdd-logo.png width=300px align=right>

# Pandas introduction

The next notebooks will cover how to use the `pandas` library to explore datasets.

In this section we will cover:

* [Pandas overview](#overview)
* [Lambdas starter](#lambdas)
* [Benefits of using pandas](#benefits)
* [Data wrangling](#wrangling)
* [<mark>Exercise: Exploratory Data Analysis</mark>](#exploring)
    * [<mark>Exercise: Learn some key methods!</mark>](#exploring)
    * [<mark>Exercise: Explore a dataset</mark>](#ex-explore-data)
* [Analysis](#analysis)

<a id = 'lambdas'></a>
## <mark>Exercise: Lambda Starter</mark>

**Lambda functions** really start to come into their own when we use them with pandas. Therefore we need to be really comfortable with the syntax. 

Here is an example of a lambda function that adds 4 to a number:

In [ ]:
add_4 = lambda x: x + 4

In [ ]:
add_4(10)

This lambda function essentially does the same as if we were formally defining a function.

In [ ]:
def add_4(x):
    return x + 4

In [ ]:
add_4(10)

We can also define multiple parameters in a lambda function by a separating comma:

In [ ]:
add_4y = lambda x, y: x + 4*y

In [ ]:
add_4y(10, y = 2)

Now complete the following questions:

1. Create a lambda function that multiplies two numbers together (and check it)

2. Create a lambda function to check if a number is bigger than 10 (and check it)

<a id = 'overview'></a>
## Pandas overview

Pandas is a specialised package that allows you to work with tabular data using python.

First you need to import the package:

In [1]:
import pandas as pd

Then, to read in a csv file you can use:
```python
pd.read_csv('filepath/file.csv')
```

This notebook uses the `chickweight.csv` dataset, which is in the `data/` folder:

In [3]:
df = pd.read_csv('data/chickweight.csv')

In [7]:
df["time"]

KeyError: 'time'

Aside from making tables look prettier in your Jupyter notebook, there are many advantages for using the Pandas packages when working with data.

<a id = 'benefits'></a>

## The benefits of using Pandas (and Python)

**Question:** What kind of benefits do you think you have using `pandas` to work with data?

<details>
    <summary><font color=blue>Show answer</font></summary>

- **Automation**: You can automate otherwise tedious tasks such as merging multiple datasets.
- **Cleaning**: Pandas allows you to automate the cleaning of your datasets.
- **Speed**: When working with large datasets, it is much faster than tools like Excel.
- **Filtering**: Easy to filter to find specific values
- **Groupby**: Chunk your data set into pieces, apply a function, and place it back together
- **Creating new columns**: Easily create new columns from calculations with other columns

    
*And much more!*

</details>


<a id = 'wrangling'></a>

## Data wrangling with Pandas

**Data Wrangling** is the process of transforming and mapping data, with the intent of making it more appropriate and valuable for a variety of downstream purposes such as for dashboards or analytics.

To demonstrate pandas' capabilities, let's load the `chickweight.csv` dataset.

In [ ]:
df["4"] = df["Diet"]

df.rename(str.lower, axis='columns')

TypeError: descriptor 'lower' for 'str' objects doesn't apply to a 'int' object

In [22]:
chickweight = pd.read_csv('data/chickweight.csv').rename(str.lower, axis='columns')

chickweight.head()

   rownum  weight  time  chick  diet
0       1      42     0      1     1
1       2      51     2      1     1
2       3      59     4      1     1
3       4      64     6      1     1
4       5      76     8      1     1

<a id = 'exploring'></a>
## <mark> Exercise: Exploratory Data Analysis</mark>

### <mark>Part 1: Learn some key attributes/methods!</mark>

Fill in the comments to explain what each cell does **in your own words**. 

You can use `help(pd.DataFrame.X)` to access the documentation for the attribute/method. For example,

```python
help(chickweight.info)
```

The first one is done for you.

In [23]:
# the shape attribute... gives the number of rows and number of columns
chickweight.shape

(578, 5)

In [24]:
# the info method...
chickweight.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 578 entries, 0 to 577
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   rownum  578 non-null    int64
 1   weight  578 non-null    int64
 2   time    578 non-null    int64
 3   chick   578 non-null    int64
 4   diet    578 non-null    int64
dtypes: int64(5)
memory usage: 22.7 KB

In [25]:
# the descibe method...
chickweight.describe()

           rownum      weight        time       chick        diet
count  578.000000  578.000000  578.000000  578.000000  578.000000
mean   289.500000  121.818339   10.717993   25.750865    2.235294
std    166.998503   71.071960    6.758400   14.568795    1.162678
min      1.000000   35.000000    0.000000    1.000000    1.000000
25%    145.250000   63.000000    4.000000   13.000000    1.000000
50%    289.500000  103.000000   10.000000   26.000000    2.000000
75%    433.750000  163.750000   16.000000   38.000000    3.000000
max    578.000000  373.000000   21.000000   50.000000    4.000000

In [26]:
# the index columns...
chickweight.columns

Index(['rownum', 'weight', 'time', 'chick', 'diet'], dtype='object')

In [27]:
# the head method...
chickweight.head()

   rownum  weight  time  chick  diet
0       1      42     0      1     1
1       2      51     2      1     1
2       3      59     4      1     1
3       4      64     6      1     1
4       5      76     8      1     1

In [28]:
# the tail method...
chickweight.tail()

     rownum  weight  time  chick  diet
573     574     175    14     50     4
574     575     205    16     50     4
575     576     234    18     50     4
576     577     264    20     50     4
577     578     264    21     50     4

In [36]:
# the sample method...
chickweight.sample()

     rownum  weight  time  chick  diet
102     103      92    14      9     1

In [ ]:
# you can use square brackets to...
chickweight['diet']

pandas.core.series.Series

In [41]:
type(chickweight)

pandas.core.frame.DataFrame

In [42]:
# the unique method...
chickweight['diet'].unique()

array([1, 2, 3, 4])

In [43]:
# the value_counts method...
chickweight['diet'].value_counts()

diet
1    220
2    120
3    120
4    118
Name: count, dtype: int64

In [51]:
# the mean method...
chickweight.mean()

rownum    289.500000
weight    121.818339
time       10.717993
chick      25.750865
diet        2.235294
dtype: float64

<a id = 'ex-explore-data'></a>
### <mark>Part 2: Explore a dataset</mark>
Investigate the `weight` and `time` columns of the dataframe.

1. How many different unique values for `time` are there? What do you think time represents in this dataframe?

In [53]:
len(chickweight["time"].unique())

12

In [54]:
chickweight["time"].nunique()

12

2. What are the min & max of the time and weight column?

In [ ]:
chickweight["weight"].max()

373

**Bonus:** What is the most common (i.e the mode) weight of a chicken?

In [84]:
%%timeit
chickweight["weight"].value_counts().index[0]

149 μs ± 31.6 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [85]:
%%timeit
chickweight["weight"].mode().values[0]

69.3 μs ± 4.49 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [86]:
chickweight

     rownum  weight  time  chick  diet
0         1      42     0      1     1
1         2      51     2      1     1
2         3      59     4      1     1
3         4      64     6      1     1
4         5      76     8      1     1
..      ...     ...   ...    ...   ...
573     574     175    14     50     4
574     575     205    16     50     4
575     576     234    18     50     4
576     577     264    20     50     4
577     578     264    21     50     4

[578 rows x 5 columns]

### Answers


<details>
    <summary><font style=font-weight:bold>Part 1:</font>
        <font color=blue>Show answer</font></summary>
  
Using exploration includes:

* Checking the shape (`df.shape`) of the dataframe
* The length (`len(df)`) of the dataframe
* General information (`df.info()`) of the dataframe & columns
* Averages of each numeric column (`df.describe()`)
* The column names (`df.columns`)
* Fetching the first/last or a sample of a few rows (`.head()` `df.sample()` `df.tail()`)
* Selecting one (or more) columns (`df['column_name']`)
* Fetching the unique values of a column (`df['column_name'].unique()`)
* Summing the amount of unique values of a column (`df['column_name'].value_counts()`)

</details>


**Part 2:** Uncomment (remove the `# `) and run the cell to see the solution.

In [ ]:
# %load answers/01_Introduction/ex-explore-data-1.py

In [ ]:
# %load answers/01_Introduction/ex-explore-data-2.py

In [ ]:
# %load answers/01_Introduction/ex-explore-data-3.py

<a id = 'analysis'></a>
## Analysis

### What analysis could you do? 


<img src="images/01_Introduction/chick.png" width="240" height="240" align="center"/>

Imagine that you own a farm and have this dataset available.

Now you have a feel for the dataset, what could you do with it?

In [ ]:
chickweight.head()

### Potential areas for analysis:

Some questions you might want to answer are:

1. Which diet is best for our chickens?
2. How quickly do our chickens grow over time?
3. Which chickens are the best growers?
4. Can we predict how much a chicken will grow depending on diet and starting weight?

The main use case could be to figure out which diet is best, but it is good to think about some of the other use cases.